In [1]:
import numpy as np

In [ ]:
np.random.seed(0)

## Slow loops

In [5]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1,10, size=5)

In [6]:
values

array([1, 4, 4, 8, 4])

In [7]:
compute_reciprocals(values)

array([1.   , 0.25 , 0.25 , 0.125, 0.25 ])

Let's do it on larger lists...

In [9]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

4.48 s ± 511 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Vectorizing Code

In [11]:
1.0 / values

array([1.   , 0.25 , 0.25 , 0.125, 0.25 ])

In [23]:
%timeit 1.0 / big_array

3.28 ms ± 252 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Non-scalars

In [17]:
a1 = np.arange(5)
a2 = np.arange(1, 6)

In [18]:
a1

array([0, 1, 2, 3, 4])

In [19]:
a2

array([1, 2, 3, 4, 5])

In [22]:
a1 / a2

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

### 2D

In [24]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

## Arithmetic Examples

In [27]:
a1 

array([0, 1, 2, 3, 4])

In [28]:
a1 + 5

array([5, 6, 7, 8, 9])

In [29]:
a1 - 5

array([-5, -4, -3, -2, -1])

In [30]:
a1 * 2

array([0, 2, 4, 6, 8])

In [31]:
a1 / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [35]:
a1 // 2 

array([0, 0, 1, 1, 2])

In [32]:
a1 ** 2

array([ 0,  1,  4,  9, 16])

In [34]:
2 ** a1

array([ 1,  2,  4,  8, 16])

In [36]:
-a1

array([ 0, -1, -2, -3, -4])

In [39]:
a1 % 3

array([0, 1, 2, 0, 1])

String them together

In [42]:
2 % (1 + ((a1 * 2) / 5))

array([0. , 0.6, 0.2, 2. , 2. ])

In [43]:
2 % (1 + ((big_array * 2) / 5))

array([2., 2., 2., ..., 2., 2., 2.])

all these operators are available in np:

In [44]:
np.add(a1, 2)

array([2, 3, 4, 5, 6])

In [47]:
%timeit np.abs(big_array)

1.41 ms ± 198 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [48]:
%timeit abs(big_array)

1.51 ms ± 141 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


complex numbers:

In [51]:
c = 3 - 4j
np.abs(c)

5.0

## Trigonometric functions

In [57]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [58]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [59]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [60]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

Inverse

In [61]:
x = [-1, 0, 1]

In [62]:
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [63]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [64]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

Exp and log

In [68]:
x = [1,2,3]
np.exp(x) # e^1, e^2, e^3

array([ 2.71828183,  7.3890561 , 20.08553692])

In [69]:
np.exp2(x) # 2^...

array([2., 4., 8.])

In [70]:
np.power(3, x) # 3^x

array([ 3,  9, 27])

In [71]:
np.power(x, 3) # x^3

array([ 1,  8, 27])

In [72]:
x = [1,2,4,10]

In [73]:
np.log(x)

array([0.        , 0.69314718, 1.38629436, 2.30258509])

In [74]:
np.log2(x)

array([0.        , 1.        , 2.        , 3.32192809])

In [75]:
np.log10(x)

array([0.        , 0.30103   , 0.60205999, 1.        ])

Small input precision.
When x is very small, these functions give more precise values than if the raw np.log or np.exp were used.

In [77]:
x = [0, 0.001, 0.01, 0.1]
np.expm1(x)

array([0.        , 0.0010005 , 0.01005017, 0.10517092])

In [78]:
np.log1p(x)

array([0.        , 0.0009995 , 0.00995033, 0.09531018])

Special functions: scipy.special

## Advanced features

specifying output

In [94]:
size = 10
x = np.arange(size)
y = np.empty(size)
np.multiply(x, 10, out=y)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [100]:
y = np.zeros(size*2) # note the double size
np.power(2, x, out=y[::2])
y

array([  1.,   0.,   2.,   0.,   4.,   0.,   8.,   0.,  16.,   0.,  32.,
         0.,  64.,   0., 128.,   0., 256.,   0., 512.,   0.])

## Aggregates

In [102]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [103]:
np.add.reduce(x)

15

In [104]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

## Outer products

In [105]:
x = np.arange(1,6)

In [106]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])