# Broadcasting

In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2])
b = np.array([5,5,5])
a + b

array([5, 6, 7])

## Scalar broadcasting

In [ ]:
a + 5

## N-D Broadcasting 
broadcast a 1D array over a 2D

In [5]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

## Different shapes

In [10]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

In [11]:
a

array([0, 1, 2])

In [12]:
b

array([[0],
       [1],
       [2]])

In [13]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [18]:
np.ones((3,1)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])