# Matrix Operations
not present in the book

In [2]:
import numpy as np

In [61]:
A = np.arange(12).reshape((4,3))
B = np.arange(12).reshape((3,4))

In [44]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
def calculate_cell(A, B, rowA, colB, n):
    result = 0
    for i in range(n):
        term = A[rowA][i] * B[i][colB]
        result += term
    return result

def mydot(A, B):
    rows = len(A)
    cols = len(B[0])
    n = len(B)
    
    result = []
    for i in range(rows):
        for j in range(cols):
            result.append(calculate_cell(A, B, i, j, n))
    
    return np.array(result).reshape((rows,cols))
    

In [47]:
def mydot2(A, B):
    rows = len(A)
    cols = len(B[0])
    n = len(B)
    
    result = []
    for i in range(rows):
        for j in range(cols):
            cell = 0
            for k in range(n):
                term = A[i][k] * B[k][j]
                cell += term
            result.append(cell)
    
    return np.array(result).reshape((rows,cols))
    

In [59]:
def mydot3(A, B):
    rows = len(A)
    cols = len(B[0])
    n = len(B)
    
    result = np.zeros((rows,cols))
    for i in range(rows):
        for j in range(cols):
            for k in range(n):
                result[i,j] += A[i][k] * B[k][j]
    
    return result
    

In [60]:
def mydot4(A, B):
    rows = len(A)
    cols = len(B[0])
    n = len(B)
    
    result = np.zeros((rows,cols))
    for i in range(rows):
        for k in range(n):
            for j in range(cols):
                result[i,j] += A[i][k] * B[k][j]
    
    return result
    

In [48]:
A.dot(B)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [49]:
mydot(A,B)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [50]:
mydot2(A,B)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [62]:
mydot3(A,B)

array([[ 20.,  23.,  26.,  29.],
       [ 56.,  68.,  80.,  92.],
       [ 92., 113., 134., 155.],
       [128., 158., 188., 218.]])

In [63]:
mydot4(A,B)

array([[ 20.,  23.,  26.,  29.],
       [ 56.,  68.,  80.,  92.],
       [ 92., 113., 134., 155.],
       [128., 158., 188., 218.]])

In [64]:
%timeit A.dot(B)
%timeit mydot(A,B)
%timeit mydot2(A,B)
%timeit mydot3(A,B)
%timeit mydot4(A,B)

1.09 µs ± 53 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
52.1 µs ± 2.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
51 µs ± 1.58 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
62.5 µs ± 2.15 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
60 µs ± 2.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [65]:
A = np.arange(2000).reshape(40,50)
B = np.arange(2000).reshape(50,40)

In [66]:
%timeit A.dot(B)
%timeit mydot(A,B)
%timeit mydot2(A,B)
%timeit mydot3(A,B)
%timeit mydot4(A,B)

85.2 µs ± 7.07 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
58.5 ms ± 1.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
58.2 ms ± 1.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
88.3 ms ± 8.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
86.3 ms ± 3.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
