# Numpy Tests

In [65]:
from IPython.core.interactiveshell import InteractiveShell
# output all the statements in a cell
InteractiveShell.ast_node_interactivity = "all"

## Arrays
arrays in python are fixed-type lists

In [1]:
import array

In [3]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
array.array('i',l)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Numpy
numpy arrays will have efficient storage

In [6]:
import numpy as np

In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
# upcasts will happen!
np.array([1.2,3])

array([1.2, 3. ])

In [12]:
# explicit types
np.array([1,2,3], dtype='float32') # or np.float32

array([1., 2., 3.], dtype=float32)

From scratch

In [15]:
np.zeros(10, dtype=np.int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.full((4,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [25]:
np.arange(1,10,1) # half-open interval

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.linspace(0,10,5) # closed interval, equally-spaced points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
np.random.random((3,2))

array([[0.94914541, 0.45358847],
       [0.72245697, 0.57001262],
       [0.95143273, 0.03573244]])

In [49]:
np.random.randint(0,10,(3,4)) # half-open

array([[9, 8, 6, 4],
       [7, 9, 1, 7],
       [4, 8, 8, 0]])

In [36]:
np.random.normal(0,1,(3,3))

array([[-1.09112229, -0.4864675 ,  0.17715801],
       [ 0.6436595 ,  0.72358651, -0.49423149],
       [ 0.16882606, -0.82156044, -0.85441357]])

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.empty(3) # no initialization takes place! we take data that is in the memory!

array([6.94096937e-310, 6.94096937e-310, 1.58101007e-322])

Attributes

In [63]:
x1 = np.random.randint(10, size=None)
x2 = np.random.randint(10, size=1)
x3 = np.random.randint(10, size=6)
x4 = np.random.randint(10, size=(3,2))
x5 = np.random.randint(10, size=(3,4,5))

In [67]:
x1
x2
x3
x4
x5

0

array([5])

array([8, 3, 0, 1, 0, 4])

array([[2, 9],
       [4, 0],
       [1, 9]])

array([[[7, 4, 8, 2, 1],
        [4, 0, 3, 9, 6],
        [1, 1, 9, 7, 3],
        [9, 4, 3, 6, 6]],

       [[5, 3, 6, 8, 6],
        [1, 6, 0, 5, 8],
        [7, 8, 4, 0, 0],
        [7, 5, 1, 1, 1]],

       [[8, 9, 0, 2, 9],
        [7, 1, 5, 4, 3],
        [8, 6, 5, 1, 1],
        [7, 0, 3, 4, 0]]])

In [77]:
x4
x4.ndim
x4.shape
x4.size
x4.itemsize
x4.nbytes

array([[2, 9],
       [4, 0],
       [1, 9]])

2

(3, 2)

6

8

48

Slicing

In [119]:
x = np.random.randint(0,10,(3,3))
x

array([[4, 3, 4],
       [0, 3, 9],
       [7, 6, 1]])

In [133]:
x[:,1] # all rows, second colum
x[0,:] # row 0
x[0] # row 0
x[1:,:] # rows 1 and beyond
x[1:] # rows 1 and beyond

array([3, 3, 6])

array([4, 3, 4])

array([4, 3, 4])

array([[0, 3, 9],
       [7, 6, 1]])

array([[0, 3, 9],
       [7, 6, 1]])

In [121]:
x[0].copy()

array([4, 3, 4])

In [122]:
x.reshape((1,9))
x.reshape((1,9))[0][1]
x.reshape((1,9))[0,1]

array([[4, 3, 4, 0, 3, 9, 7, 6, 1]])

3

3

In [123]:
one_d = x[0]
one_d[np.newaxis,:] # make row vector
one_d.reshape((1,3))# make row vector
one_d[:,np.newaxis] # make col vector
one_d.reshape((3,1))# make col vector
x[:1][:np.newaxis] # make col vector

array([[4, 3, 4]])

array([[4, 3, 4]])

array([[4],
       [3],
       [4]])

array([[4],
       [3],
       [4]])

array([[4, 3, 4]])

concat and split

In [137]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [138]:
x + y

array([5, 7, 9])

In [139]:
np.concatenate([x, y, x])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [140]:
two_d = np.array([[1,2,3],
                  [4,5,6]])

In [141]:
np.concatenate([two_d,two_d])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [142]:
np.concatenate([two_d,two_d], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [143]:
np.concatenate([two_d,two_d], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [144]:
np.vstack([x, two_d])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [153]:
l = x[1:][:,np.newaxis] # col vector is needed!
l
np.hstack([two_d, l])

array([[2],
       [3]])

array([[1, 2, 3, 2],
       [4, 5, 6, 3]])

splitting

In [154]:
l = np.arange(1,10)
l.split()